// ルノルマン 36 枚カードデータ
// Flutter MoonCycle アプリの LenormandDeck から移植

export const LENORMAND_CARDS = [
  {
    id: 1,
    name: 'THE RIDER',
    nameJa: '騎手',
    nameZhTW: '騎士',
    file: '01-rider.png',
    keyword: '訪問・ニュース・速さ',
    keywordZhTW: '訪客・消息・速度',
    meaning: '新しいニュースや訪問者の到来。物事が急速に動き始める兆し。',
    meaningZhTW: '新消息或訪客即將到來。事情開始快速推進的預兆。',
  },
  {
    id: 2,
    name: 'THE CLOVER',
    nameJa: 'クローバー',
    nameZhTW: '幸運草',
    file: '02-clover.png',
    keyword: '幸運・チャンス・軽やかさ',
    keywordZhTW: '幸運・機緣・輕盈',
    meaning: '小さな幸運と予期せぬチャンス。軽やかに流れに乗る時。',
    meaningZhTW: '小小的幸運與意外的機緣。輕盈地順著流動前進的時機。',
  },
  {
    id: 3,
    name: 'THE SHIP',
    nameJa: '船',
    nameZhTW: '船',
    file: '03-ship.png',
    keyword: '旅・変化・遠距離',
    keywordZhTW: '旅途・變化・遠距離',
    meaning: '新しい旅立ちや変化の時。遠くからのつながりも示す。',
    meaningZhTW: '新的啟程或變化的時刻。也暗示來自遠方的連結。',
  },
  {
    id: 4,
    name: 'THE HOUSE',
    nameJa: '家',
    nameZhTW: '家',
    file: '04-house.png',
    keyword: '家族・安定・プライベート',
    keywordZhTW: '家庭・穩定・私人',
    meaning: '家庭と安定の領域。プライベートな空間と家族との絆。',
    meaningZhTW: '家庭與穩定的領域。私人空間與家人之間的羈絆。',
  },
  {
    id: 5,
    name: 'THE TREE',
    nameJa: '樹木',
    nameZhTW: '大樹',
    file: '05-tree.png',
    keyword: '成長・健康・生命力',
    keywordZhTW: '成長・健康・生命力',
    meaning: '深く根を張る成長。健康と生命力、長期的な発展。',
    meaningZhTW: '深深扎根的成長。健康與生命力，長期的發展。',
  },
  {
    id: 6,
    name: 'THE CLOUDS',
    nameJa: '雲',
    nameZhTW: '雲',
    file: '06-clouds.png',
    keyword: '不明瞭・混乱・待機',
    keywordZhTW: '不明朗・混亂・等待',
    meaning: '状況が不明瞭な時期。焦らず嵐が過ぎるのを待つ。',
    meaningZhTW: '情況不明朗的時期。不要焦急，等待風暴過去。',
  },
  {
    id: 7,
    name: 'THE SNAKE',
    nameJa: '蛇',
    nameZhTW: '蛇',
    file: '07-snake.png',
    keyword: '変容・知恵・複雑さ',
    keywordZhTW: '蛻變・智慧・複雜',
    meaning: '変容と深い知恵のエネルギー。複雑な状況の中の洞察。',
    meaningZhTW: '蛻變與深層智慧的能量。複雜情況中的洞察力。',
  },
  {
    id: 8,
    name: 'THE COFFIN',
    nameJa: '棺',
    nameZhTW: '棺木',
    file: '08-coffin.png',
    keyword: '終わり・手放し・変容',
    keywordZhTW: '終結・放下・蛻變',
    meaning: '一つの時期の終焉。古いものを手放し変容する時。',
    meaningZhTW: '一個時期的終結。放下舊有事物、迎接蛻變的時刻。',
  },
  {
    id: 9,
    name: 'THE BOUQUET',
    nameJa: '花束',
    nameZhTW: '花束',
    file: '09-bouquet.png',
    keyword: '喜び・感謝・美しさ',
    keywordZhTW: '喜悅・感恩・美麗',
    meaning: '喜びと美しさの到来。感謝と祝福のエネルギー。',
    meaningZhTW: '喜悅與美麗的到來。感恩與祝福的能量。',
  },
  {
    id: 10,
    name: 'THE SCYTHE',
    nameJa: '鎌',
    nameZhTW: '鐮刀',
    file: '10-scythe.png',
    keyword: '決断・切断・速さ',
    keywordZhTW: '決斷・切斷・迅速',
    meaning: '素早い決断が必要な時。不要なものを刈り取る。',
    meaningZhTW: '需要迅速做決定的時刻。割捨不必要的事物。',
  },
  {
    id: 11,
    name: 'THE WHIP',
    nameJa: '鞭',
    nameZhTW: '鞭',
    file: '11-whip.png',
    keyword: '葛藤・繰り返し・情熱',
    keywordZhTW: '葛藤・反覆・熱情',
    meaning: '繰り返すパターンや葛藤。情熱的なエネルギーの発露。',
    meaningZhTW: '反覆的模式或葛藤。熱情能量的迸發。',
  },
  {
    id: 12,
    name: 'THE BIRDS',
    nameJa: '鳥',
    nameZhTW: '鳥',
    file: '12-owl.png',
    keyword: '洞察・秘密・夜',
    keywordZhTW: '洞察・秘密・夜晚',
    meaning: '深い洞察力と知恵。夜の神秘と隠された真実。',
    meaningZhTW: '深層的智慧與洞察力。夜晚的神秘與隱藏的真相。',
  },
  {
    id: 13,
    name: 'THE CHILD',
    nameJa: '子供',
    nameZhTW: '孩子',
    file: '13-child.png',
    keyword: '新しい始まり・純粋・好奇心',
    keywordZhTW: '新的開始・純粹・好奇心',
    meaning: '新しい始まりと純粋さ。好奇心と可能性に満ちた出発。',
    meaningZhTW: '新的開始與純粹。充滿好奇心與可能性的出發。',
  },
  {
    id: 14,
    name: 'THE FOX',
    nameJa: '狐',
    nameZhTW: '狐狸',
    file: '14-fox.png',
    keyword: '賢さ・適応・慎重',
    keywordZhTW: '聰明・適應・謹慎',
    meaning: '賢さと適応力。状況を読んで慎重に動く時。',
    meaningZhTW: '聰明才智與適應力。讀懂局勢、謹慎行動的時機。',
  },
  {
    id: 15,
    name: 'THE BEAR',
    nameJa: '熊',
    nameZhTW: '熊',
    file: '15-bear.png',
    keyword: '守護・豊かさ・力強さ',
    keywordZhTW: '守護・豐盛・力量',
    meaning: '強い守護のエネルギー。物質的な豊かさと強さ。',
    meaningZhTW: '強大的守護能量。物質的豐盛與強大的力量。',
  },
  {
    id: 16,
    name: 'THE STARS',
    nameJa: '星',
    nameZhTW: '星星',
    file: '16-stars.png',
    keyword: '希望・宇宙・導き',
    keywordZhTW: '希望・宇宙・引導',
    meaning: '希望の光と宇宙からの導き。夢に向かって進む力。',
    meaningZhTW: '希望之光與宇宙的引導。朝著夢想前進的力量。',
  },
  {
    id: 17,
    name: 'THE STORK',
    nameJa: 'コウノトリ',
    nameZhTW: '鸛鳥',
    file: '17-stork.png',
    keyword: '変化・移動・新展開',
    keywordZhTW: '變化・移動・新發展',
    meaning: '新しい展開と前向きな変化。より良い場所への移動。',
    meaningZhTW: '新的發展與正向的變化。向更好的地方移動。',
  },
  {
    id: 18,
    name: 'THE DOG',
    nameJa: '犬',
    nameZhTW: '狗',
    file: '18-dog.png',
    keyword: '友情・信頼・忠実',
    keywordZhTW: '友情・信任・忠實',
    meaning: '深い信頼と友情。忠実なサポートと安心感。',
    meaningZhTW: '深厚的信任與友情。忠實的支持與安心感。',
  },
  {
    id: 19,
    name: 'THE TOWER',
    nameJa: '塔',
    nameZhTW: '塔',
    file: '19-tower.png',
    keyword: '孤独・権威・展望',
    keywordZhTW: '孤獨・權威・展望',
    meaning: '権威や組織との関わり。孤独の中の洞察と展望。',
    meaningZhTW: '與權威或組織的關聯。孤獨中的洞察與展望。',
  },
  {
    id: 20,
    name: 'THE GARDEN',
    nameJa: '庭',
    nameZhTW: '花園',
    file: '20-garden.png',
    keyword: '社交・公共・出会い',
    keywordZhTW: '社交・公共・相遇',
    meaning: '人々との交流と社会的なつながり。公の場での活動。',
    meaningZhTW: '與人們的交流和社會連結。在公開場合的活動。',
  },
  {
    id: 21,
    name: 'THE MOUNTAIN',
    nameJa: '山',
    nameZhTW: '山',
    file: '21-mountain.png',
    keyword: '障害・忍耐・克服',
    keywordZhTW: '障礙・耐心・克服',
    meaning: '乗り越えるべき障害。忍耐と努力で道が開ける。',
    meaningZhTW: '需要克服的障礙。耐心與努力終將開花結果。',
  },
  {
    id: 22,
    name: 'THE CROSSROADS',
    nameJa: '十字路',
    nameZhTW: '十字路口',
    file: '22-crossroads.png',
    keyword: '選択・決断・直感',
    keywordZhTW: '選擇・決斷・直覺',
    meaning: '重要な選択の岐路。直感を信じて道を選ぶ時。',
    meaningZhTW: '重要選擇的十字路口。相信直覺選擇道路的時刻。',
  },
  {
    id: 23,
    name: 'THE MICE',
    nameJa: 'ネズミ',
    nameZhTW: '老鼠',
    file: '23-mice.png',
    keyword: '消耗・不安・手放し',
    keywordZhTW: '消耗・不安・放下',
    meaning: 'じわじわと消耗するエネルギー。不安や心配を手放して。',
    meaningZhTW: '緩緩消耗的能量。放下不安與擔憂。',
  },
  {
    id: 24,
    name: 'THE HEART',
    nameJa: 'ハート',
    nameZhTW: '心',
    file: '24-heart.png',
    keyword: '愛・情熱・深いつながり',
    keywordZhTW: '愛・熱情・深厚連結',
    meaning: '愛と感情の核心。心からの情熱と深いつながり。',
    meaningZhTW: '愛與情感的核心。發自內心的熱情與深厚連結。',
  },
  {
    id: 25,
    name: 'THE RING',
    nameJa: '指輪',
    nameZhTW: '戒指',
    file: '25-ring.png',
    keyword: '約束・継続・サイクル',
    keywordZhTW: '承諾・持續・週期',
    meaning: '約束と続くつながり。サイクルの完結。',
    meaningZhTW: '承諾與持續的連結。循環週期的完結。',
  },
  {
    id: 26,
    name: 'THE BOOK',
    nameJa: '本',
    nameZhTW: '書本',
    file: '26-book.png',
    keyword: '知識・秘密・学び',
    keywordZhTW: '知識・秘密・學習',
    meaning: '隠れた知識と学びの時。秘密が明かされる予感。',
    meaningZhTW: '隱藏的知識與學習的時刻。秘密即將揭曉的預兆。',
  },
  {
    id: 27,
    name: 'THE LETTER',
    nameJa: '手紙',
    nameZhTW: '信件',
    file: '27-letter.png',
    keyword: 'メッセージ・文書・コミュニケーション',
    keywordZhTW: '訊息・文件・溝通',
    meaning: '重要なメッセージや文書の到来。言葉によるつながり。',
    meaningZhTW: '重要訊息或文件的到來。透過文字建立的連結。',
  },
  {
    id: 28,
    name: 'THE MAN',
    nameJa: '男性',
    nameZhTW: '男性',
    file: '28-gentleman.png',
    keyword: '男性・意志・行動力',
    keywordZhTW: '男性・意志・行動力',
    meaning: '重要な男性との関わり。意志と行動力のエネルギー。',
    meaningZhTW: '與重要男性的關聯。意志與行動力的能量。',
  },
  {
    id: 29,
    name: 'THE WOMAN',
    nameJa: '女性',
    nameZhTW: '女性',
    file: '29-lady.png',
    keyword: '女性・直感・受容',
    keywordZhTW: '女性・直覺・接納',
    meaning: '重要な女性との関わり。直感と受容のエネルギー。',
    meaningZhTW: '與重要女性的關聯。直覺與接納的能量。',
  },
  {
    id: 30,
    name: 'THE LILY',
    nameJa: 'ユリ',
    nameZhTW: '百合',
    file: '30-lily.png',
    keyword: '純粋・調和・精神的成熟',
    keywordZhTW: '純粹・和諧・精神成熟',
    meaning: '深い静けさと精神的な成熟。純粋さと調和のエネルギー。',
    meaningZhTW: '深沉的平靜與精神上的成熟。純粹與和諧的能量。',
  },
  {
    id: 31,
    name: 'THE SUN',
    nameJa: '太陽',
    nameZhTW: '太陽',
    file: '31-sun.png',
    keyword: '成功・活力・明晰さ',
    keywordZhTW: '成功・活力・清晰',
    meaning: '輝かしい成功と活力。明晰なビジョンとポジティブなエネルギー。',
    meaningZhTW: '燦爛的成功與活力。清晰的視野與正向的能量。',
  },
  {
    id: 32,
    name: 'THE MOON',
    nameJa: '月',
    nameZhTW: '月亮',
    file: '32-moon.png',
    keyword: '直感・夢・潜在意識',
    keywordZhTW: '直覺・夢境・潛意識',
    meaning: '深い直感と夢のメッセージ。感受性と潜在意識の知恵。',
    meaningZhTW: '深層的直覺與夢境訊息。感受性與潛意識的智慧。',
  },
  {
    id: 33,
    name: 'THE KEY',
    nameJa: '鍵',
    nameZhTW: '鑰匙',
    file: '33-key.png',
    keyword: '解決・答え・開放',
    keywordZhTW: '解決・答案・開放',
    meaning: '重要な答えと解決策。新しい可能性への扉が開く。',
    meaningZhTW: '重要的答案與解決方案。通往新可能性的門扉開啟。',
  },
  {
    id: 34,
    name: 'THE FISH',
    nameJa: '魚',
    nameZhTW: '魚',
    file: '34-fish.png',
    keyword: '豊かさ・ビジネス・流れ',
    keywordZhTW: '豐盛・商業・流動',
    meaning: '豊かな流れとビジネスの発展。直感的に流れに乗る時。',
    meaningZhTW: '豐盛的流動與商業發展。憑直覺順流而行的時刻。',
  },
  {
    id: 35,
    name: 'THE ANCHOR',
    nameJa: '碇',
    nameZhTW: '錨',
    file: '35-anchor.png',
    keyword: '安定・定着・目標',
    keywordZhTW: '穩定・定著・目標',
    meaning: '長期的な安定と目標への固執。根を張る力強さ。',
    meaningZhTW: '長期的的穩定與目標的堅持。紮根的強大力量。',
  },
  {
    id: 36,
    name: 'THE CROSS',
    nameJa: '十字架',
    nameZhTW: '十字架',
    file: '36-cross.png',
    keyword: '運命・試練・信仰',
    keywordZhTW: '命運・考驗・信念',
    meaning: '避けられない運命と試練。信仰と受容によって乗り越える。',
    meaningZhTW: '無可避免的命運與考驗。透過信念與接納來超越。',
  },
] as const

export type LenormandCard = (typeof LENORMAND_CARDS)[number]

/** id からカードを引く（見つからなければ undefined） */
export function getCardById(id: number): LenormandCard | undefined {
  return LENORMAND_CARDS.find((c) => c.id === id)
}

/** 36 枚をシャッフルして n 枚返す */
export function drawCards(n: number): LenormandCard[] {
  const shuffled = [...LENORMAND_CARDS].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, n)
}
